/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package karkov.ui.buttonRequest;

import karkov.models.Request;
import karkov.repository.RepositoryRequest;
import karkov.ui.Home;
import karkov.ui.showRequest.AddRequestPanel;
import karkov.ui.showRequest.SearchRequest;
import karkov.ui.showRequest.ShowPanel;

import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author blackhawk
 */
public class HommeAssist extends javax.swing.JPanel {

    /**
     * Creates new form HommeAssist
     */
    public HommeAssist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAssist = new javax.swing.JPanel();
        addRequestButon = new javax.swing.JButton();
        showRequestsButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();

        panelAssist.setBackground(new java.awt.Color(33, 158, 188));

        addRequestButon.setBackground(new java.awt.Color(255, 183, 3));
        addRequestButon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addRequestButon.setForeground(new java.awt.Color(0, 0, 0));
        addRequestButon.setText("Add Request");
        addRequestButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRequestButonActionPerformed(evt);
            }
        });

        showRequestsButton.setBackground(new java.awt.Color(255, 183, 3));
        showRequestsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        showRequestsButton.setForeground(new java.awt.Color(0, 0, 0));
        showRequestsButton.setText("Show Requests");
        showRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRequestsButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(255, 183, 3));
        searchButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setText("Search Request");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAssistLayout = new javax.swing.GroupLayout(panelAssist);
        panelAssist.setLayout(panelAssistLayout);
        panelAssistLayout.setHorizontalGroup(
            panelAssistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAssistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addRequestButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showRequestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAssistLayout.setVerticalGroup(
            panelAssistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAssistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addRequestButon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAssist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAssist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRequestButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRequestButonActionPerformed
        //xd
        AddRequestPanel addRequestPanel = new AddRequestPanel();
        addRequestPanel.setSize(1416, 102);
        addRequestPanel.setLocation(0, 0);
        Home.superiorPanel.removeAll();
        Home.superiorPanel.add(addRequestPanel, BorderLayout.CENTER);
        Home.superiorPanel.revalidate();
        Home.superiorPanel.repaint();
    }//GEN-LAST:event_addRequestButonActionPerformed

    private void searchButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // T
        SearchRequest searchRequest = new SearchRequest();
        searchRequest.setSize(1416, 102);
        searchRequest.setLocation(0, 0);
        Home.superiorPanel.removeAll();
        Home.superiorPanel.add(searchRequest, BorderLayout.CENTER);
        Home.superiorPanel.revalidate();

        for(Request request : RepositoryRequest.getRequestArray()){
            String idS = String.valueOf(request.getId());
            SearchRequest.searchIdComboBox.addItem(idS);
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void showRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRequestsButtonActionPerformed
        ShowPanel showPanel = new ShowPanel();
        showPanel.setSize(1033, 756);
        showPanel.setLocation(0, 0);


        Home.centerPanel.removeAll();
        Home.centerPanel.add(showPanel, BorderLayout.CENTER);
        Home.centerPanel.revalidate();
        Home.centerPanel.repaint();

        Home.superiorPanel.removeAll();
        Home.superiorPanel.add(new HomeDriver(), BorderLayout.CENTER);
        Home.superiorPanel.revalidate();
        Home.superiorPanel.repaint();

        ShowPanel.makeSortTable(1);
    }//GEN-LAST:event_showRequestsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRequestButon;
    private javax.swing.JPanel panelAssist;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showRequestsButton;
    // End of variables declaration//GEN-END:variables
}
