/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package karkov.ui.showRequest;

/**
 *
 * @author blackhawk
 */
public class AddRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddRequestPanel
     */
    public AddRequestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        addRequestPanel = new javax.swing.JPanel();
        zoneComboBox = new javax.swing.JComboBox<>();
        aptNumberComboBox = new javax.swing.JComboBox<>();
        priorityComboBox = new javax.swing.JComboBox<>();
        limitTimeTextField = new javax.swing.JTextField();
        addRequestButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addRequestPanel.setBackground(new java.awt.Color(142, 202, 230));

        zoneComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zone", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J" }));
        zoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneComboBoxActionPerformed(evt);
            }
        });

        aptNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apt", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13", "14", "15", "16" }));
        aptNumberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aptNumberComboBoxActionPerformed(evt);
            }
        });

        priorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Priority", "Alta", "Media", "Baja" }));

        limitTimeTextField.setText("Limit time");
        limitTimeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                limitTimeTextFieldFocusGained(evt);
            }
        });

        addRequestButton.setText("Add Request");

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add Request:");

        javax.swing.GroupLayout addRequestPanelLayout = new javax.swing.GroupLayout(addRequestPanel);
        addRequestPanel.setLayout(addRequestPanelLayout);
        addRequestPanelLayout.setHorizontalGroup(
            addRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRequestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addRequestPanelLayout.createSequentialGroup()
                        .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aptNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limitTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(addRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(834, Short.MAX_VALUE))
        );
        addRequestPanelLayout.setVerticalGroup(
            addRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRequestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addRequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aptNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limitTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRequestButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addRequestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addRequestPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void zoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneComboBoxActionPerformed

    private void aptNumberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aptNumberComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aptNumberComboBoxActionPerformed

    private void limitTimeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_limitTimeTextFieldFocusGained
        // TODO add your handling code here:
        limitTimeTextField.setText("");
        
    }//GEN-LAST:event_limitTimeTextFieldFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRequestButton;
    private javax.swing.JPanel addRequestPanel;
    private javax.swing.JComboBox<String> aptNumberComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField limitTimeTextField;
    private javax.swing.JComboBox<String> priorityComboBox;
    private javax.swing.JComboBox<String> zoneComboBox;
    // End of variables declaration//GEN-END:variables
}
