/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package karkov.ui.showRequest;

import karkov.models.Request;
import karkov.repository.RepositoryRequest;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author blackhawk
 */
public class RuteRequest extends javax.swing.JPanel {

    /**
     * Creates new form RuteRequest
     */
    public RuteRequest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rutePanel = new javax.swing.JPanel();
        ruteLabel = new javax.swing.JLabel();
        ruteComboBox = new javax.swing.JComboBox<>();

        rutePanel.setBackground(new java.awt.Color(33, 158, 188));

        ruteLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ruteLabel.setForeground(new java.awt.Color(0, 0, 0));
        ruteLabel.setText("From: centro");

        ruteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rute" }));

        javax.swing.GroupLayout rutePanelLayout = new javax.swing.GroupLayout(rutePanel);
        rutePanel.setLayout(rutePanelLayout);
        rutePanelLayout.setHorizontalGroup(
            rutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(ruteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ruteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1082, Short.MAX_VALUE))
        );
        rutePanelLayout.setVerticalGroup(
            rutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(rutePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruteLabel)
                    .addComponent(ruteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rutePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> ruteComboBox;
    private javax.swing.JLabel ruteLabel;
    private javax.swing.JPanel rutePanel;
    // End of variables declaration//GEN-END:variables
}
